"""Stable machine-readable error codes."""

from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    # Input shape / limits
    INVALID_REQUEST = "E1001_INVALID_REQUEST"
    INVALID_RATIONAL = "E1002_INVALID_RATIONAL"
    PEAK_COUNT_OUT_OF_RANGE = "E1003_PEAK_COUNT_OUT_OF_RANGE"
    PEAKS_NOT_STRICTLY_INCREASING = "E1004_PEAKS_NOT_STRICTLY_INCREASING"
    PEAK_POSITION_NOT_POSITIVE = "E1005_PEAK_POSITION_NOT_POSITIVE"
    TOLERANCE_NOT_POSITIVE = "E1006_TOLERANCE_NOT_POSITIVE"
    IMPURITY_QUOTA_OUT_OF_RANGE = "E1007_IMPURITY_QUOTA_OUT_OF_RANGE"
    LIMIT_OUT_OF_RANGE = "E1008_LIMIT_OUT_OF_RANGE"
    # Solver outcome
    NO_SOLUTION = "E2001_NO_SOLUTION"
    COMPUTATION_LIMIT_EXCEEDED = "E2002_COMPUTATION_LIMIT_EXCEEDED"
    # Certificate verification
    CERTIFICATE_MALFORMED = "E3001_CERTIFICATE_MALFORMED"
    CERTIFICATE_TAMPERED = "E3002_CERTIFICATE_TAMPERED"
    CERTIFICATE_REQUEST_MISMATCH = "E3003_CERTIFICATE_REQUEST_MISMATCH"
    # Generic
    INTERNAL_ERROR = "E5000_INTERNAL_ERROR"
    NOT_FOUND = "E4004_NOT_FOUND"
